[[main]]
  name = "Programação"
  pageRef = "schedule"
  weight = 10

[[main]]
  name = "Materiais"
  pageRef = "materials"
  weight = 20

[[main]]
  name = "Inscrever-se"
  url = "https://example.com"
  weight = 30
  [main.params]
    target = "_blank"

[[footer]]
  name = "Instagram"
  url = "https://instagram.com/impact_rio"
  [footer.params]
    icon = "instagram"
    showName = true
    target = "_blank"

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/impact-rio/"
  [footer.params]
    icon = "linkedin"
    showName = true
    target = "_blank"
