colorScheme = "impact-rio"
defaultAppearance = "dark"
enableSearch = true

[homepage]
  layout = "page"
  showRecent = false

[article]
  showPagination = false
  showDate = false
  showBreadcrumbs = false
  showAuthor = false

[header]
  logo = "impact-rio.png"
  layout = "hybrid"

[footer]
  showCopyright = true
  showThemeAttribution = false
